Create Contributing.md
aheacon/school_enrollment pull request #1
Opened 2023-02-15 16:51 UTC by omarkopcha

My contribution in order to understand these steps explained in the file.

2023-02-15 17:36 UTC, aheacon requested changes

2023-02-15 17:36 UTC, aheacon commented on Contributing.md
> +
@omarkopcha  molim te napisi korake sta radis.
Za markdown koda, koristi block code:  ``` enter <napisi kod> enter ``` , a za code inline koristi ``
Npr.
1. Najprije kloniramo direktorij sa komandom `git clone`
```bash
$ git clone
```

2023-02-19 15:30 UTC, omarkopcha commented
[Contributing.md](https://github.com/aheacon/school_enrollment/files/10777243/Contributing.md)

2023-02-20 09:33 UTC, aheacon commented
Omare, nije patch da posaljes file u komentar.
Trebas napraviti novi commit.
1. Uradi promjene u odnosu na commit ff42641afadaaa2b9131c3ddc83c73b306c99203
2. `git status` da vidis promjene
3. `git add .`
4. `git commit -m "Bolji markdown"` - > ovdje dobijes novi commit hash npr. `deadbeef`
Nakon toga trebao bi da imas 2 commit-a na branch `patch-1`.
Sad imas 2 opcije:
1. Push: `git push origin patch-1` (trebalo bi da radi ako imas samo 2 nova commita :  ff42641afadaa i deadbeef u odnosu na zadnji commit na `master` branch
2. Ukoliko ne bude radilo 1. onda `git push origin patch-1 -f ` -  force push
Postoji jos jedna opcija, da dobijes samo 1 commit, sto se radi sa `git rebase`, ali necemo sad to.

Vezano sa markdown
1. Instaliraj Visual Studio Code
2. Kad instaliras navigiraj se na mjesto gdje ti je projekat
3. Iz terminala pokreni komanud `$ code .`
4. Otvori `contributing.md` file
5. Desnim klikom na taj file, trebalo bi da vidis Preview tog file

2024-02-05 11:13 UTC, closed without merging