Learning 1
aheacon/school_enrollment pull request #2
Opened 2024-02-02 14:34 UTC by Faariis

Added some text about fixtures and how to add them. And added tests. More in README.

2024-02-05 11:18 UTC, aheacon requested changes
@Faariis , hvala na PR-u.
Mozes li molim te napraviti 1 commit i ukratko da editujes title i description PR-a, sta PR zapravo radi?

2024-02-05 13:47 UTC, aheacon requested changes

2024-02-05 13:47 UTC, aheacon commented on README.md
> +Fixture predstavlja skup podataka koje Django unosi u bazu podataka.
Molim te koristi englesku terminlogiju, da ne mijesamo malo engleski, malo bosanski :).

2024-02-05 13:47 UTC, aheacon commented on README.md
> +'python manage.py loaddata naziv_fixture.json' npr. u našem slučaju kao primjer:
Koristi  \` \`  za komande

2024-02-05 13:47 UTC, aheacon commented on myEnrollment/myEnrollment/settings.py
> +import dotenv
Mislim da ovo ne treba. Env varijable se trebaju manuelno ubaciti, radi sigurnosti i ocekivanog rada. Bolje je da se dobije greska, zbog nepostojeceg env-a, nego da radi sa mozda ne-updateovanim env-om.

2024-02-05 13:47 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +
Ovo ok, 2 new line  izmedju funkcija.

2024-02-05 13:47 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +from django.contrib.auth import get_user_model
Zasto ovo ?

2024-02-05 14:18 UTC, Faariis commented on myEnrollment/teachersAuth/tests.py
> +from django.contrib.auth import get_user_model
Kod provjere rute za email verifikaciju. Koristim: user = get_user_model().objects.get(email="a@a"), morao sam imporzovat.

2024-02-05 14:23 UTC, Faariis commented on myEnrollment/teachersAuth/tests.py
> +  # Getting data of the school using canton code [our case SA] (passed)
Dobro, stavit ću da sve bude tako.

2024-02-05 14:24 UTC, Faariis commented on myEnrollment/teachersAuth/tests.py
> +
Al ako izbacim bude sad greška.

2024-02-05 14:29 UTC, Faariis commented on myEnrollment/teachersAuth/tests.py
> +    self.teacher.is_active= True # this deosn't affect
Ako je False ne radi. Pretpostavljam jer onda znači da korisnik nije aktivan. Kad je true mogu mogu normalno testove izvršavat.
is active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False
Fis active:  False , kad pokrenem.

2024-02-05 14:33 UTC, Faariis commented on myEnrollment/myEnrollment/settings.py
> +
Ovo mi je trebalo zbog .env

2024-02-05 14:33 UTC, Faariis commented on README.md
> +'python manage.py loaddata naziv_fixture.json' npr. u našem slučaju kao primjer:
Uradit ću tako.

2024-02-05 14:34 UTC, Faariis commented on .gitignore
> +private_key.pem
Izbacio sam.

2024-02-05 14:34 UTC, Faariis commented on README.md
> +Fixture predstavlja skup podataka koje Django unosi u bazu podataka.
Prebacit ću na engleski.

2024-02-06 20:43 UTC, aheacon requested changes

2024-02-06 20:43 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +  def test_get_canton_by_schools(self):
Ovo treba sve prebaciti u `secondary-schools.test.py`. Uskoro cu updateovati sa novim commitom, pa ces vidjeti.

2024-02-06 21:55 UTC, Faariis commented on myEnrollment/teachersAuth/tests.py
> +  def test_get_canton_by_schools(self):
Razumijem, da bude sve što je vezano za srednje škole u tests.py za secondarySchools, a kod teachers tests.py da ostane login, ispis profesora, itd.

2024-02-09 10:37 UTC, aheacon requested changes

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/secondarySchools/tests.py
> +    """
Ostavi ono sto je dobro u testu.
Dobro u test je biokomentar i test koji je radio.
Ovaj ovdje dio je samo wrapper u funkciji postojeceg test.
```
# UPDATE with NULL (200) - this emulates create
# Put should change from null to value (as done in postman) - works
```

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/secondarySchools/tests.py
> +    self.assertEqual(resp.status_code, status.HTTP_204_NO_CONTENT, resp.data)
Tek ovdje je `deleted` i mozes dodati komenatr.

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/secondarySchools/tests.py
> +    self.assertIsNone(delete_canton)
Ubaci u except, jer inace u oba slucaja ce vratiti `None`.

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/secondarySchools/urls.py
> +    path('canton/schools/detail/<int:pk>/', CantonSchoolDetailView.as_view(), name="canton-school-detail"),
Napravi poseban commit za ovo i stavi test koji se odnosi na ovaj url zajedno sa tim commitom.

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +      #print ("Teacher: "+ t.get_short_name() + " password set!")
Komentarisan komentar nam ne treba.

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +  def test_create_teacher_list_not_allowed(self):
Ukini ovo

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +  def test_update_teacher_list_not_allowed(self):
I ovo izbrisi.

2024-02-09 10:37 UTC, aheacon commented on myEnrollment/teachersAuth/tests.py
> +    url = reverse('teacher-detail', args = (self.teacher.id,))
Provjeri da li je teacher super_user. I ako jeste napisi da je ovo test za superusera.
Dodaj novi test gdje ces napraviti novog teachera koji nije superuser i treba test da faila sa resp.data key=message i text user not authorized.

2024-02-10 01:17 UTC, closed without merging